import "./globals.css";
import type { Metadata } from "next";
import { ysebeauFont } from "./font";
import Grid from "@/components/ui/Grid/component";
import { ThemeToggle } from "@/components/theme/theme-toggle";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { StackNavigator } from "@/components/stack/stack-navigator";

export const metadata: Metadata = {
  title: "Soikat UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="layout">
        <ThemeProvider
          enableSystem
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
        >
          <Grid container>
            <Grid item xs={12}>
              <div className="appbar">
                <p className={ysebeauFont.className}>Soikat UI</p>
                <ThemeToggle />
              </div>
            </Grid>
            <Grid item xs={2}>
              <div className={`sidebar ${ysebeauFont.className}`}>
                <StackNavigator />
              </div>
            </Grid>
            <Grid item xs={10}>
              <div className="content-wrapper">{children}</div>
            </Grid>
          </Grid>
        </ThemeProvider>
      </body>
    </html>
  );
}
